
version: '3.9'

services:
    nocodb:
        container_name: nocodb
        restart: always
        image: nocodb/nocodb:latest
        volumes:
            - inventory_data:/usr/app/data/
        ports:
            - "8080:8080"

volumes:
    inventory_data: